export const contractRevision = 4;
export const managementCapabilities = Object.freeze(['open_verified_parent', 'open_no_follow', 'read_identity', 'read_acl', 'path_exists_no_follow', 'set_exact_role_acl', 'verify_exact_role_acl', 'read_verified_bytes', 'create_exclusive_temp', 'flush_file', 'flush_directory_or_volume', 'replace_existing_atomic', 'create_absent_exclusive', 'ensure_control_directory', 'acquire_native_lock', 'current_os_principal', 'principal_access_check', 'remove_verified_file', 'open_verified_parent_handle', 'open_verified_object_handle', 'read_handle_identity', 'read_handle_bytes', 'write_handle_bytes', 'remove_verified_handle', 'verify_role_sid_not_group']);
export const inventoryCapabilities = Object.freeze([
  'resolve_native_state_root',
  'read_workspace_root_facts',
  'ensure_inventory_directory',
  'verify_inventory_acl',
  'acquire_inventory_fence',
  'read_inventory_object',
  'publish_inventory_object_atomic',
]);
// Workspace-serving low-level capabilities (slice S7.2). enumerate_workspace_
// process_holders backs the residual-process absence proof consumed before a
// reset/delete generation teardown. Real scan is Linux-only in this slice; the
// Windows handle-scan is registered but unsupported until slice S7.2b.
export const servingCapabilities = Object.freeze([
  'enumerate_workspace_process_holders',
]);
export const serviceCapabilities = Object.freeze([
  'set_exact_service_acl',
  'verify_exact_service_acl',
  'read_file_facts_no_follow',
  'read_boot_id',
  'read_process_facts',
  'enumerate_process_tree',
  'read_linux_service_cgroup',
  'terminate_linux_service_cgroup',
  'open_win32_service',
  'close_win32_service',
  'query_win32_service',
  'create_win32_service_disabled',
  'protect_win32_service',
  'set_win32_service_marker',
  'configure_win32_service_launch',
  'set_win32_service_start_type',
  'set_win32_service_failure_actions',
  'set_win32_service_failure_actions_flag',
  'start_win32_service',
  'stop_win32_service',
  'delete_win32_service',
  'terminate_win32_service_tree',
  'open_service_root',
  'open_service_directory',
  'acquire_service_lock',
  'close_service_handle',
  'read_service_file',
  'publish_service_file_atomic',
  'remove_service_object_exact',
  'list_service_directory',
  'publish_service_directory_no_replace',
  'open_linux_service_scope',
  'read_linux_service_object',
  'publish_linux_service_object',
  'remove_linux_service_object',
  'begin_service_artifact_write',
  'write_service_artifact_chunk',
  'finish_service_artifact_write',
  'open_service_artifact_reader',
  'read_service_artifact_chunk',
  'remove_service_artifact_file_exact',
  'seal_service_directory',
  'open_service_artifact_source',
]);
export const capabilities = Object.freeze([
  ...managementCapabilities,
  ...inventoryCapabilities,
  ...servingCapabilities,
  ...serviceCapabilities,
]);
export const capabilitySignatures = Object.freeze({
  open_verified_parent: ['path'], open_no_follow: ['path'], read_identity: ['path'], read_acl: ['path'], path_exists_no_follow: ['path'],
  set_exact_role_acl: ['path', 'managementSid', 'botSid', 'recoverySid', 'systemSid', 'profile'],
  verify_exact_role_acl: ['path', 'managementSid', 'botSid', 'recoverySid', 'systemSid', 'profile'],
  read_verified_bytes: ['path'], create_exclusive_temp: ['parent', 'prefix', 'bytes', 'managementSid', 'botSid', 'recoverySid', 'systemSid', 'profile'],
  flush_file: ['path'], flush_directory_or_volume: ['path'],
  replace_existing_atomic: ['source', 'destination', 'managementSid', 'botSid', 'recoverySid', 'systemSid', 'profile'],
  create_absent_exclusive: ['path', 'bytes', 'managementSid', 'botSid', 'recoverySid', 'systemSid', 'profile'],
  ensure_control_directory: ['path', 'managementSid', 'botSid', 'recoverySid', 'systemSid', 'profile'],
  acquire_native_lock: ['path', 'managementSid', 'botSid', 'recoverySid', 'systemSid', 'profile'],
  current_os_principal: [], principal_access_check: ['path', 'kind', 'principal', 'mode', 'managementSid', 'botSid', 'recoverySid', 'systemSid', 'profile'], remove_verified_file: ['path', 'expectedBytes'],
  open_verified_parent_handle: ['path'], open_verified_object_handle: ['parentHandle', 'name'],
  read_handle_identity: ['handle'], read_handle_bytes: ['handle'], write_handle_bytes: ['handle', 'bytes'],
  remove_verified_handle: ['handle', 'expectedBytes'],
  verify_role_sid_not_group: ['sid'],
  resolve_native_state_root: ['hostKey', 'rootKind'],
  read_workspace_root_facts: ['path', 'sourcePlatform'],
  ensure_inventory_directory: ['path', 'roles', 'profile'],
  verify_inventory_acl: ['path', 'roles', 'profile', 'expectedActor'],
  acquire_inventory_fence: ['path', 'roles'],
  read_inventory_object: ['path', 'maxBytes', 'roles', 'profile'],
  publish_inventory_object_atomic: ['path', 'tempPrefix', 'bytes', 'expectedIdentity', 'roles', 'profile'],
  enumerate_workspace_process_holders: ['workDir', 'sourcePlatform'],
  set_exact_service_acl: ['path', 'roles', 'profile'],
  verify_exact_service_acl: ['path', 'roles', 'profile'],
  read_file_facts_no_follow: ['path', 'maxBytes'],
  read_boot_id: [],
  read_process_facts: ['pid'],
  enumerate_process_tree: ['rootPid', 'rootStartTime', 'rootExecutable', 'rootOwner'],
  read_linux_service_cgroup: ['cgroupPath'],
  terminate_linux_service_cgroup: ['cgroupPath', 'expectedDevice', 'expectedInode', 'expectedTreeFingerprint'],
  open_win32_service: ['name', 'serviceRole', 'roles', 'access'],
  close_win32_service: ['serviceHandle'],
  query_win32_service: ['serviceHandle'],
  create_win32_service_disabled: ['name', 'serviceRole', 'supervisorPath', 'supervisorSha256', 'workingDirectory', 'homeDirectory', 'runtimePath', 'runtimeSha256', 'entrypointPath', 'entrypointSha256', 'logDirectory', 'logAs', 'logCmdAs', 'channelsConfig', 'servicePassword', 'roles'],
  protect_win32_service: ['serviceHandle', 'expectedConfigFingerprint', 'expectedRuntimeFingerprint', 'transitionMarker'],
  set_win32_service_marker: ['serviceHandle', 'expectedConfigFingerprint', 'expectedRuntimeFingerprint', 'transitionMarker'],
  configure_win32_service_launch: ['serviceHandle', 'expectedConfigFingerprint', 'expectedRuntimeFingerprint', 'supervisorPath', 'supervisorSha256', 'workingDirectory', 'homeDirectory', 'runtimePath', 'runtimeSha256', 'entrypointPath', 'entrypointSha256', 'logDirectory', 'logAs', 'logCmdAs', 'channelsConfig'],
  set_win32_service_start_type: ['serviceHandle', 'expectedConfigFingerprint', 'expectedRuntimeFingerprint', 'startType'],
  set_win32_service_failure_actions: ['serviceHandle', 'expectedConfigFingerprint', 'expectedRuntimeFingerprint', 'failurePolicy'],
  set_win32_service_failure_actions_flag: ['serviceHandle', 'expectedConfigFingerprint', 'expectedRuntimeFingerprint', 'enabled'],
  start_win32_service: ['serviceHandle', 'expectedConfigFingerprint', 'expectedRuntimeFingerprint'],
  stop_win32_service: ['serviceHandle', 'expectedConfigFingerprint', 'expectedRuntimeFingerprint'],
  delete_win32_service: ['serviceHandle', 'expectedConfigFingerprint', 'expectedRuntimeFingerprint'],
  terminate_win32_service_tree: ['serviceHandle', 'expectedConfigFingerprint', 'rootPid', 'rootStartTime', 'rootExecutable', 'rootOwner', 'expectedTreeFingerprint'],
  open_service_root: ['rootKind', 'roles', 'access'],
  open_service_directory: ['parentHandle', 'name', 'access', 'expectedIdentity', 'lockHandle'],
  acquire_service_lock: ['controlRootHandle', 'scope', 'serviceKey', 'mode'],
  close_service_handle: ['handle'],
  read_service_file: ['parentHandle', 'name', 'maxBytes'],
  publish_service_file_atomic: ['parentHandle', 'name', 'bytes', 'expected', 'lockHandle'],
  remove_service_object_exact: ['parentHandle', 'name', 'expected', 'lockHandle'],
  list_service_directory: ['directoryHandle', 'maxEntries', 'lockHandle'],
  publish_service_directory_no_replace: ['sourceDirectoryHandle', 'destinationParentHandle', 'name', 'expectedSourceIdentity', 'artifactLockHandle'],
  open_linux_service_scope: ['roles', 'serviceKey', 'access'],
  read_linux_service_object: ['scopeHandle', 'objectKind'],
  publish_linux_service_object: ['scopeHandle', 'objectKind', 'bytes', 'expected', 'lockHandle'],
  remove_linux_service_object: ['scopeHandle', 'objectKind', 'expected', 'lockHandle'],
  begin_service_artifact_write: ['parentHandle', 'name', 'expectedSize', 'expectedSha256', 'artifactLockHandle'],
  write_service_artifact_chunk: ['writerHandle', 'expectedOffset', 'bytes'],
  finish_service_artifact_write: ['writerHandle', 'finalProfile'],
  open_service_artifact_reader: ['parentHandle', 'name', 'maxBytes', 'expectedFacts', 'artifactLockHandle'],
  read_service_artifact_chunk: ['readerHandle', 'expectedOffset', 'maxBytes'],
  remove_service_artifact_file_exact: ['parentHandle', 'name', 'expectedFacts', 'artifactLockHandle'],
  seal_service_directory: ['directoryHandle', 'expectedIdentity', 'artifactLockHandle'],
  open_service_artifact_source: ['path', 'maxBytes', 'expectedFacts', 'roles'],
});
for (const signature of Object.values(capabilitySignatures)) Object.freeze(signature);
